# Generated by Django 2.2.6 on 2020-06-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_name', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=200)),
                ('url_params', models.CharField(blank=True, max_length=200, null=True)),
                ('supported_http_actions', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
